// Code generated by protoc-gen-go. DO NOT EDIT.
// source: yolo_grpc.proto

/*
Package plates_recognition_grpc is a generated protocol buffer package.

It is generated from these files:
	yolo_grpc.proto

It has these top-level messages:
	CamInfo
	Detection
	Response
*/
package plates_recognition_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CamInfo struct {
	CamId     string     `protobuf:"bytes,1,opt,name=cam_id,json=camId" json:"cam_id,omitempty"`
	Timestamp int64      `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Image     []byte     `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Detection *Detection `protobuf:"bytes,4,opt,name=detection" json:"detection,omitempty"`
}

func (m *CamInfo) Reset()                    { *m = CamInfo{} }
func (m *CamInfo) String() string            { return proto.CompactTextString(m) }
func (*CamInfo) ProtoMessage()               {}
func (*CamInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CamInfo) GetCamId() string {
	if m != nil {
		return m.CamId
	}
	return ""
}

func (m *CamInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CamInfo) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *CamInfo) GetDetection() *Detection {
	if m != nil {
		return m.Detection
	}
	return nil
}

type Detection struct {
	XLeft  int32 `protobuf:"varint,1,opt,name=x_left,json=xLeft" json:"x_left,omitempty"`
	YTop   int32 `protobuf:"varint,2,opt,name=y_top,json=yTop" json:"y_top,omitempty"`
	Height int32 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Width  int32 `protobuf:"varint,4,opt,name=width" json:"width,omitempty"`
}

func (m *Detection) Reset()                    { *m = Detection{} }
func (m *Detection) String() string            { return proto.CompactTextString(m) }
func (*Detection) ProtoMessage()               {}
func (*Detection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Detection) GetXLeft() int32 {
	if m != nil {
		return m.XLeft
	}
	return 0
}

func (m *Detection) GetYTop() int32 {
	if m != nil {
		return m.YTop
	}
	return 0
}

func (m *Detection) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Detection) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type Response struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Warning string `protobuf:"bytes,2,opt,name=warning" json:"warning,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetWarning() string {
	if m != nil {
		return m.Warning
	}
	return ""
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CamInfo)(nil), "plates_recognition_grpc.CamInfo")
	proto.RegisterType((*Detection)(nil), "plates_recognition_grpc.Detection")
	proto.RegisterType((*Response)(nil), "plates_recognition_grpc.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for STYolo service

type STYoloClient interface {
	SendDetection(ctx context.Context, in *CamInfo, opts ...grpc.CallOption) (*Response, error)
}

type sTYoloClient struct {
	cc *grpc.ClientConn
}

func NewSTYoloClient(cc *grpc.ClientConn) STYoloClient {
	return &sTYoloClient{cc}
}

func (c *sTYoloClient) SendDetection(ctx context.Context, in *CamInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/plates_recognition_grpc.STYolo/SendDetection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for STYolo service

type STYoloServer interface {
	SendDetection(context.Context, *CamInfo) (*Response, error)
}

func RegisterSTYoloServer(s *grpc.Server, srv STYoloServer) {
	s.RegisterService(&_STYolo_serviceDesc, srv)
}

func _STYolo_SendDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CamInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STYoloServer).SendDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plates_recognition_grpc.STYolo/SendDetection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STYoloServer).SendDetection(ctx, req.(*CamInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _STYolo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plates_recognition_grpc.STYolo",
	HandlerType: (*STYoloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDetection",
			Handler:    _STYolo_SendDetection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yolo_grpc.proto",
}

func init() { proto.RegisterFile("yolo_grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4e, 0xf3, 0x30,
	0x0c, 0xc0, 0xbf, 0x7e, 0x5b, 0x3a, 0x6a, 0x40, 0x48, 0xe1, 0x5f, 0x85, 0x38, 0x94, 0x9e, 0x7a,
	0xda, 0x61, 0xbc, 0x00, 0x12, 0x5c, 0x26, 0x71, 0xca, 0x26, 0x24, 0x4e, 0x25, 0xb4, 0x5e, 0x17,
	0xa9, 0x89, 0xab, 0x34, 0xd2, 0xb6, 0x17, 0xe1, 0x79, 0x51, 0xd3, 0x95, 0x9d, 0x7a, 0xfc, 0xd9,
	0x4e, 0xfc, 0xb3, 0x0d, 0x57, 0x07, 0xaa, 0x29, 0xaf, 0x6c, 0x53, 0xcc, 0x1b, 0x4b, 0x8e, 0xf8,
	0x7d, 0x53, 0x4b, 0x87, 0x6d, 0x6e, 0xb1, 0xa0, 0xca, 0x28, 0xa7, 0xc8, 0xf8, 0x74, 0xfa, 0x13,
	0xc0, 0xec, 0x55, 0xea, 0xa5, 0xd9, 0x10, 0xbf, 0x85, 0xb0, 0x90, 0x3a, 0x57, 0x65, 0x1c, 0x24,
	0x41, 0x16, 0x09, 0x56, 0x48, 0xbd, 0x2c, 0xf9, 0x23, 0x44, 0x4e, 0x69, 0x6c, 0x9d, 0xd4, 0x4d,
	0xfc, 0x3f, 0x09, 0xb2, 0x89, 0x38, 0x05, 0xf8, 0x0d, 0x30, 0xa5, 0x65, 0x85, 0xf1, 0x24, 0x09,
	0xb2, 0x0b, 0xd1, 0x03, 0x7f, 0x81, 0xa8, 0x44, 0x87, 0x45, 0xd7, 0x28, 0x9e, 0x26, 0x41, 0x76,
	0xbe, 0x48, 0xe7, 0x23, 0x0e, 0xf3, 0xb7, 0xa1, 0x52, 0x9c, 0x1e, 0xa5, 0x08, 0xd1, 0x5f, 0xbc,
	0x33, 0xdb, 0xe7, 0x35, 0x6e, 0x9c, 0x37, 0x63, 0x82, 0xed, 0xdf, 0x71, 0xe3, 0xf8, 0x35, 0xb0,
	0x43, 0xee, 0xa8, 0xb7, 0x62, 0x62, 0x7a, 0x58, 0x53, 0xc3, 0xef, 0x20, 0xdc, 0xa2, 0xaa, 0xb6,
	0xce, 0x1b, 0x31, 0x71, 0xa4, 0x4e, 0x74, 0xa7, 0x4a, 0xb7, 0xf5, 0x3a, 0x4c, 0xf4, 0x90, 0xae,
	0xe1, 0x4c, 0x60, 0xdb, 0x90, 0x69, 0x91, 0xc7, 0x30, 0xd3, 0xd8, 0xb6, 0xdd, 0x30, 0xfd, 0x02,
	0x06, 0xec, 0x32, 0x3b, 0x69, 0x8d, 0x32, 0x95, 0x6f, 0x15, 0x89, 0x01, 0xbb, 0x5f, 0xd1, 0x5a,
	0xb2, 0xbe, 0x59, 0x24, 0x7a, 0x58, 0x7c, 0x41, 0xb8, 0x5a, 0x7f, 0x52, 0x4d, 0xfc, 0x03, 0x2e,
	0x57, 0x68, 0xca, 0xd3, 0x28, 0xc9, 0xe8, 0x1a, 0x8e, 0x67, 0x78, 0x78, 0x1a, 0xad, 0x18, 0x4c,
	0xd3, 0x7f, 0xdf, 0xa1, 0xbf, 0xeb, 0xf3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xe0, 0xcd,
	0xf6, 0xea, 0x01, 0x00, 0x00,
}
