// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: object.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Essential information to process
type LPRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Bytes representation of image (PNG)
	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Optional information about image. Could be usefull if client-side already knows where license plate should be located (due some object detections technique)
	Bbox *BBox `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
}

func (x *LPRRequest) Reset() {
	*x = LPRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPRRequest) ProtoMessage() {}

func (x *LPRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPRRequest.ProtoReflect.Descriptor instead.
func (*LPRRequest) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{0}
}

func (x *LPRRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *LPRRequest) GetBbox() *BBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

// Reference information about detection rectangle
type BBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XLeft  int32 `protobuf:"varint,1,opt,name=x_left,json=xLeft,proto3" json:"x_left,omitempty"`
	YTop   int32 `protobuf:"varint,2,opt,name=y_top,json=yTop,proto3" json:"y_top,omitempty"`
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width  int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
}

func (x *BBox) Reset() {
	*x = BBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_object_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BBox) ProtoMessage() {}

func (x *BBox) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BBox.ProtoReflect.Descriptor instead.
func (*BBox) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{1}
}

func (x *BBox) GetXLeft() int32 {
	if x != nil {
		return x.XLeft
	}
	return 0
}

func (x *BBox) GetYTop() int32 {
	if x != nil {
		return x.YTop
	}
	return 0
}

func (x *BBox) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BBox) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

// Response from server
type LPRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Set of found license plates with corresponding information
	LicensePlates []*LPRInfo `protobuf:"bytes,1,rep,name=license_plates,json=licensePlates,proto3" json:"license_plates,omitempty"`
	// Number of seconds has taken to proccess license plate detections and OCR
	Elapsed float32 `protobuf:"fixed32,2,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	// Optional message from server
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Optional warning message from server. If it is not empty you probably should investiage such behavior
	Warning string `protobuf:"bytes,4,opt,name=warning,proto3" json:"warning,omitempty"`
	// Optional error message from server. If it is not empty you should investiage the error
	Error string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *LPRResponse) Reset() {
	*x = LPRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_object_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPRResponse) ProtoMessage() {}

func (x *LPRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPRResponse.ProtoReflect.Descriptor instead.
func (*LPRResponse) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{2}
}

func (x *LPRResponse) GetLicensePlates() []*LPRInfo {
	if x != nil {
		return x.LicensePlates
	}
	return nil
}

func (x *LPRResponse) GetElapsed() float32 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

func (x *LPRResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LPRResponse) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

func (x *LPRResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Information about single license plate
type LPRInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// License plate location
	Bbox *BBox `protobuf:"bytes,1,opt,name=bbox,proto3" json:"bbox,omitempty"`
	// License plate OCR bounding bboxes. Bounding bboxes are sorted by horizontal line
	// Warning: those coordinates are relative to license plate bounding box, not the parent image!
	OcrBboxes []*BBox `protobuf:"bytes,2,rep,name=ocr_bboxes,json=ocrBboxes,proto3" json:"ocr_bboxes,omitempty"`
	// License plate text
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *LPRInfo) Reset() {
	*x = LPRInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_object_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPRInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPRInfo) ProtoMessage() {}

func (x *LPRInfo) ProtoReflect() protoreflect.Message {
	mi := &file_object_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPRInfo.ProtoReflect.Descriptor instead.
func (*LPRInfo) Descriptor() ([]byte, []int) {
	return file_object_proto_rawDescGZIP(), []int{3}
}

func (x *LPRInfo) GetBbox() *BBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *LPRInfo) GetOcrBboxes() []*BBox {
	if x != nil {
		return x.OcrBboxes
	}
	return nil
}

func (x *LPRInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_object_proto protoreflect.FileDescriptor

var file_object_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19,
	0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65,
	0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x57, 0x0a, 0x0a, 0x4c, 0x50, 0x52,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a,
	0x04, 0x62, 0x62, 0x6f, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x69,
	0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x6f,
	0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x42, 0x6f, 0x78, 0x52, 0x04, 0x62, 0x62,
	0x6f, 0x78, 0x22, 0x60, 0x0a, 0x04, 0x42, 0x42, 0x6f, 0x78, 0x12, 0x15, 0x0a, 0x06, 0x78, 0x5f,
	0x6c, 0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x78, 0x4c, 0x65, 0x66,
	0x74, 0x12, 0x13, 0x0a, 0x05, 0x79, 0x5f, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x79, 0x54, 0x6f, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x22, 0xbc, 0x01, 0x0a, 0x0b, 0x4c, 0x50, 0x52, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0e, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6c,
	0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x50, 0x52, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0d, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x92, 0x01, 0x0a, 0x07, 0x4c, 0x50, 0x52, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x33, 0x0a, 0x04, 0x62, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65,
	0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x42, 0x6f, 0x78, 0x52, 0x04,
	0x62, 0x62, 0x6f, 0x78, 0x12, 0x3e, 0x0a, 0x0a, 0x6f, 0x63, 0x72, 0x5f, 0x62, 0x62, 0x6f, 0x78,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x69, 0x63, 0x65, 0x6e,
	0x73, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x42, 0x6f, 0x78, 0x52, 0x09, 0x6f, 0x63, 0x72, 0x42, 0x62,
	0x6f, 0x78, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_object_proto_rawDescOnce sync.Once
	file_object_proto_rawDescData = file_object_proto_rawDesc
)

func file_object_proto_rawDescGZIP() []byte {
	file_object_proto_rawDescOnce.Do(func() {
		file_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_object_proto_rawDescData)
	})
	return file_object_proto_rawDescData
}

var file_object_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_object_proto_goTypes = []interface{}{
	(*LPRRequest)(nil),  // 0: license_plate_recognition.LPRRequest
	(*BBox)(nil),        // 1: license_plate_recognition.BBox
	(*LPRResponse)(nil), // 2: license_plate_recognition.LPRResponse
	(*LPRInfo)(nil),     // 3: license_plate_recognition.LPRInfo
}
var file_object_proto_depIdxs = []int32{
	1, // 0: license_plate_recognition.LPRRequest.bbox:type_name -> license_plate_recognition.BBox
	3, // 1: license_plate_recognition.LPRResponse.license_plates:type_name -> license_plate_recognition.LPRInfo
	1, // 2: license_plate_recognition.LPRInfo.bbox:type_name -> license_plate_recognition.BBox
	1, // 3: license_plate_recognition.LPRInfo.ocr_bboxes:type_name -> license_plate_recognition.BBox
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_object_proto_init() }
func file_object_proto_init() {
	if File_object_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_object_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_object_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_object_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_object_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPRInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_object_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_object_proto_goTypes,
		DependencyIndexes: file_object_proto_depIdxs,
		MessageInfos:      file_object_proto_msgTypes,
	}.Build()
	File_object_proto = out.File
	file_object_proto_rawDesc = nil
	file_object_proto_goTypes = nil
	file_object_proto_depIdxs = nil
}
