[server]
# gRPC server parameters
host = "0.0.0.0"
port = 50051
# Store detected object to filesytem?
save_detected = true
# Limitting recognition queue
queue_limit = 200

[yolo_plates]
# Path to ONNX model for license plate detection
model = "../data/license_plates.onnx"
# Path to class names file
names = "../data/license_plates.names"
# Model input dimensions
input_w = 416
input_h = 416
# Threshold should not be < 0.0
threshold = 0.3

[yolo_ocr]
# Path to ONNX model for OCR
model = "../data/ocr_plates.onnx"
# Path to class names file
names = "../data/ocr_plates.names"
# Model input dimensions
input_w = 416
input_h = 416
# Threshold should not be < 0.0
threshold = 0.4